// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userinfo.proto

package com.sdw.soft.demo.protobuf;

public final class UserInfo {
  private UserInfo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface UserOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.sdw.soft.demo.protobuf.User)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string name = 1;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>required int32 id = 2;</code>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 2;</code>
     */
    int getId();

    /**
     * <code>required string email = 3;</code>
     */
    boolean hasEmail();
    /**
     * <code>required string email = 3;</code>
     */
    java.lang.String getEmail();
    /**
     * <code>required string email = 3;</code>
     */
    com.google.protobuf.ByteString
        getEmailBytes();

    /**
     * <code>required .com.sdw.soft.demo.protobuf.User.PhoneNumber phone = 4;</code>
     */
    boolean hasPhone();
    /**
     * <code>required .com.sdw.soft.demo.protobuf.User.PhoneNumber phone = 4;</code>
     */
    com.sdw.soft.demo.protobuf.UserInfo.User.PhoneNumber getPhone();
    /**
     * <code>required .com.sdw.soft.demo.protobuf.User.PhoneNumber phone = 4;</code>
     */
    com.sdw.soft.demo.protobuf.UserInfo.User.PhoneNumberOrBuilder getPhoneOrBuilder();
  }
  /**
   * Protobuf type {@code com.sdw.soft.demo.protobuf.User}
   */
  public static final class User extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.sdw.soft.demo.protobuf.User)
      UserOrBuilder {
    // Use User.newBuilder() to construct.
    private User(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private User(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final User defaultInstance;
    public static User getDefaultInstance() {
      return defaultInstance;
    }

    public User getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private User(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              name_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              id_ = input.readInt32();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              email_ = bs;
              break;
            }
            case 34: {
              com.sdw.soft.demo.protobuf.UserInfo.User.PhoneNumber.Builder subBuilder = null;
              if (((bitField0_ & 0x00000008) == 0x00000008)) {
                subBuilder = phone_.toBuilder();
              }
              phone_ = input.readMessage(com.sdw.soft.demo.protobuf.UserInfo.User.PhoneNumber.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(phone_);
                phone_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000008;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sdw.soft.demo.protobuf.UserInfo.internal_static_com_sdw_soft_demo_protobuf_User_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sdw.soft.demo.protobuf.UserInfo.internal_static_com_sdw_soft_demo_protobuf_User_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sdw.soft.demo.protobuf.UserInfo.User.class, com.sdw.soft.demo.protobuf.UserInfo.User.Builder.class);
    }

    public static com.google.protobuf.Parser<User> PARSER =
        new com.google.protobuf.AbstractParser<User>() {
      public User parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new User(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<User> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code com.sdw.soft.demo.protobuf.User.PhoneType}
     */
    public enum PhoneType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>MOBILE = 0;</code>
       */
      MOBILE(0, 0),
      /**
       * <code>HOME = 1;</code>
       */
      HOME(1, 1),
      /**
       * <code>WORK = 2;</code>
       */
      WORK(2, 2),
      ;

      /**
       * <code>MOBILE = 0;</code>
       */
      public static final int MOBILE_VALUE = 0;
      /**
       * <code>HOME = 1;</code>
       */
      public static final int HOME_VALUE = 1;
      /**
       * <code>WORK = 2;</code>
       */
      public static final int WORK_VALUE = 2;


      public final int getNumber() { return value; }

      public static PhoneType valueOf(int value) {
        switch (value) {
          case 0: return MOBILE;
          case 1: return HOME;
          case 2: return WORK;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<PhoneType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<PhoneType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<PhoneType>() {
              public PhoneType findValueByNumber(int number) {
                return PhoneType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.sdw.soft.demo.protobuf.UserInfo.User.getDescriptor().getEnumTypes().get(0);
      }

      private static final PhoneType[] VALUES = values();

      public static PhoneType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private PhoneType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.sdw.soft.demo.protobuf.User.PhoneType)
    }

    public interface PhoneNumberOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.sdw.soft.demo.protobuf.User.PhoneNumber)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required string number = 1;</code>
       */
      boolean hasNumber();
      /**
       * <code>required string number = 1;</code>
       */
      java.lang.String getNumber();
      /**
       * <code>required string number = 1;</code>
       */
      com.google.protobuf.ByteString
          getNumberBytes();

      /**
       * <code>optional .com.sdw.soft.demo.protobuf.User.PhoneType type = 2 [default = HOME];</code>
       */
      boolean hasType();
      /**
       * <code>optional .com.sdw.soft.demo.protobuf.User.PhoneType type = 2 [default = HOME];</code>
       */
      com.sdw.soft.demo.protobuf.UserInfo.User.PhoneType getType();
    }
    /**
     * Protobuf type {@code com.sdw.soft.demo.protobuf.User.PhoneNumber}
     */
    public static final class PhoneNumber extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:com.sdw.soft.demo.protobuf.User.PhoneNumber)
        PhoneNumberOrBuilder {
      // Use PhoneNumber.newBuilder() to construct.
      private PhoneNumber(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private PhoneNumber(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final PhoneNumber defaultInstance;
      public static PhoneNumber getDefaultInstance() {
        return defaultInstance;
      }

      public PhoneNumber getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private PhoneNumber(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000001;
                number_ = bs;
                break;
              }
              case 16: {
                int rawValue = input.readEnum();
                com.sdw.soft.demo.protobuf.UserInfo.User.PhoneType value = com.sdw.soft.demo.protobuf.UserInfo.User.PhoneType.valueOf(rawValue);
                if (value == null) {
                  unknownFields.mergeVarintField(2, rawValue);
                } else {
                  bitField0_ |= 0x00000002;
                  type_ = value;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.sdw.soft.demo.protobuf.UserInfo.internal_static_com_sdw_soft_demo_protobuf_User_PhoneNumber_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.sdw.soft.demo.protobuf.UserInfo.internal_static_com_sdw_soft_demo_protobuf_User_PhoneNumber_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.sdw.soft.demo.protobuf.UserInfo.User.PhoneNumber.class, com.sdw.soft.demo.protobuf.UserInfo.User.PhoneNumber.Builder.class);
      }

      public static com.google.protobuf.Parser<PhoneNumber> PARSER =
          new com.google.protobuf.AbstractParser<PhoneNumber>() {
        public PhoneNumber parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new PhoneNumber(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<PhoneNumber> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      public static final int NUMBER_FIELD_NUMBER = 1;
      private java.lang.Object number_;
      /**
       * <code>required string number = 1;</code>
       */
      public boolean hasNumber() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string number = 1;</code>
       */
      public java.lang.String getNumber() {
        java.lang.Object ref = number_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            number_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string number = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNumberBytes() {
        java.lang.Object ref = number_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          number_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int TYPE_FIELD_NUMBER = 2;
      private com.sdw.soft.demo.protobuf.UserInfo.User.PhoneType type_;
      /**
       * <code>optional .com.sdw.soft.demo.protobuf.User.PhoneType type = 2 [default = HOME];</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .com.sdw.soft.demo.protobuf.User.PhoneType type = 2 [default = HOME];</code>
       */
      public com.sdw.soft.demo.protobuf.UserInfo.User.PhoneType getType() {
        return type_;
      }

      private void initFields() {
        number_ = "";
        type_ = com.sdw.soft.demo.protobuf.UserInfo.User.PhoneType.HOME;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasNumber()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getNumberBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeEnum(2, type_.getNumber());
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getNumberBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(2, type_.getNumber());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static com.sdw.soft.demo.protobuf.UserInfo.User.PhoneNumber parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.sdw.soft.demo.protobuf.UserInfo.User.PhoneNumber parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.sdw.soft.demo.protobuf.UserInfo.User.PhoneNumber parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.sdw.soft.demo.protobuf.UserInfo.User.PhoneNumber parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.sdw.soft.demo.protobuf.UserInfo.User.PhoneNumber parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.sdw.soft.demo.protobuf.UserInfo.User.PhoneNumber parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static com.sdw.soft.demo.protobuf.UserInfo.User.PhoneNumber parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static com.sdw.soft.demo.protobuf.UserInfo.User.PhoneNumber parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static com.sdw.soft.demo.protobuf.UserInfo.User.PhoneNumber parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.sdw.soft.demo.protobuf.UserInfo.User.PhoneNumber parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.sdw.soft.demo.protobuf.UserInfo.User.PhoneNumber prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code com.sdw.soft.demo.protobuf.User.PhoneNumber}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:com.sdw.soft.demo.protobuf.User.PhoneNumber)
          com.sdw.soft.demo.protobuf.UserInfo.User.PhoneNumberOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.sdw.soft.demo.protobuf.UserInfo.internal_static_com_sdw_soft_demo_protobuf_User_PhoneNumber_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.sdw.soft.demo.protobuf.UserInfo.internal_static_com_sdw_soft_demo_protobuf_User_PhoneNumber_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.sdw.soft.demo.protobuf.UserInfo.User.PhoneNumber.class, com.sdw.soft.demo.protobuf.UserInfo.User.PhoneNumber.Builder.class);
        }

        // Construct using com.sdw.soft.demo.protobuf.UserInfo.User.PhoneNumber.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          number_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          type_ = com.sdw.soft.demo.protobuf.UserInfo.User.PhoneType.HOME;
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.sdw.soft.demo.protobuf.UserInfo.internal_static_com_sdw_soft_demo_protobuf_User_PhoneNumber_descriptor;
        }

        public com.sdw.soft.demo.protobuf.UserInfo.User.PhoneNumber getDefaultInstanceForType() {
          return com.sdw.soft.demo.protobuf.UserInfo.User.PhoneNumber.getDefaultInstance();
        }

        public com.sdw.soft.demo.protobuf.UserInfo.User.PhoneNumber build() {
          com.sdw.soft.demo.protobuf.UserInfo.User.PhoneNumber result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.sdw.soft.demo.protobuf.UserInfo.User.PhoneNumber buildPartial() {
          com.sdw.soft.demo.protobuf.UserInfo.User.PhoneNumber result = new com.sdw.soft.demo.protobuf.UserInfo.User.PhoneNumber(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.number_ = number_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.type_ = type_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.sdw.soft.demo.protobuf.UserInfo.User.PhoneNumber) {
            return mergeFrom((com.sdw.soft.demo.protobuf.UserInfo.User.PhoneNumber)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.sdw.soft.demo.protobuf.UserInfo.User.PhoneNumber other) {
          if (other == com.sdw.soft.demo.protobuf.UserInfo.User.PhoneNumber.getDefaultInstance()) return this;
          if (other.hasNumber()) {
            bitField0_ |= 0x00000001;
            number_ = other.number_;
            onChanged();
          }
          if (other.hasType()) {
            setType(other.getType());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasNumber()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.sdw.soft.demo.protobuf.UserInfo.User.PhoneNumber parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.sdw.soft.demo.protobuf.UserInfo.User.PhoneNumber) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private java.lang.Object number_ = "";
        /**
         * <code>required string number = 1;</code>
         */
        public boolean hasNumber() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required string number = 1;</code>
         */
        public java.lang.String getNumber() {
          java.lang.Object ref = number_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              number_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string number = 1;</code>
         */
        public com.google.protobuf.ByteString
            getNumberBytes() {
          java.lang.Object ref = number_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            number_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string number = 1;</code>
         */
        public Builder setNumber(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          number_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string number = 1;</code>
         */
        public Builder clearNumber() {
          bitField0_ = (bitField0_ & ~0x00000001);
          number_ = getDefaultInstance().getNumber();
          onChanged();
          return this;
        }
        /**
         * <code>required string number = 1;</code>
         */
        public Builder setNumberBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          number_ = value;
          onChanged();
          return this;
        }

        private com.sdw.soft.demo.protobuf.UserInfo.User.PhoneType type_ = com.sdw.soft.demo.protobuf.UserInfo.User.PhoneType.HOME;
        /**
         * <code>optional .com.sdw.soft.demo.protobuf.User.PhoneType type = 2 [default = HOME];</code>
         */
        public boolean hasType() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>optional .com.sdw.soft.demo.protobuf.User.PhoneType type = 2 [default = HOME];</code>
         */
        public com.sdw.soft.demo.protobuf.UserInfo.User.PhoneType getType() {
          return type_;
        }
        /**
         * <code>optional .com.sdw.soft.demo.protobuf.User.PhoneType type = 2 [default = HOME];</code>
         */
        public Builder setType(com.sdw.soft.demo.protobuf.UserInfo.User.PhoneType value) {
          if (value == null) {
            throw new NullPointerException();
          }
          bitField0_ |= 0x00000002;
          type_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional .com.sdw.soft.demo.protobuf.User.PhoneType type = 2 [default = HOME];</code>
         */
        public Builder clearType() {
          bitField0_ = (bitField0_ & ~0x00000002);
          type_ = com.sdw.soft.demo.protobuf.UserInfo.User.PhoneType.HOME;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:com.sdw.soft.demo.protobuf.User.PhoneNumber)
      }

      static {
        defaultInstance = new PhoneNumber(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:com.sdw.soft.demo.protobuf.User.PhoneNumber)
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    /**
     * <code>required string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ID_FIELD_NUMBER = 2;
    private int id_;
    /**
     * <code>required int32 id = 2;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 id = 2;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int EMAIL_FIELD_NUMBER = 3;
    private java.lang.Object email_;
    /**
     * <code>required string email = 3;</code>
     */
    public boolean hasEmail() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string email = 3;</code>
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          email_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string email = 3;</code>
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PHONE_FIELD_NUMBER = 4;
    private com.sdw.soft.demo.protobuf.UserInfo.User.PhoneNumber phone_;
    /**
     * <code>required .com.sdw.soft.demo.protobuf.User.PhoneNumber phone = 4;</code>
     */
    public boolean hasPhone() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required .com.sdw.soft.demo.protobuf.User.PhoneNumber phone = 4;</code>
     */
    public com.sdw.soft.demo.protobuf.UserInfo.User.PhoneNumber getPhone() {
      return phone_;
    }
    /**
     * <code>required .com.sdw.soft.demo.protobuf.User.PhoneNumber phone = 4;</code>
     */
    public com.sdw.soft.demo.protobuf.UserInfo.User.PhoneNumberOrBuilder getPhoneOrBuilder() {
      return phone_;
    }

    private void initFields() {
      name_ = "";
      id_ = 0;
      email_ = "";
      phone_ = com.sdw.soft.demo.protobuf.UserInfo.User.PhoneNumber.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEmail()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPhone()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getPhone().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, id_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getEmailBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeMessage(4, phone_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, id_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getEmailBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, phone_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.sdw.soft.demo.protobuf.UserInfo.User parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sdw.soft.demo.protobuf.UserInfo.User parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sdw.soft.demo.protobuf.UserInfo.User parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sdw.soft.demo.protobuf.UserInfo.User parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sdw.soft.demo.protobuf.UserInfo.User parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.sdw.soft.demo.protobuf.UserInfo.User parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.sdw.soft.demo.protobuf.UserInfo.User parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.sdw.soft.demo.protobuf.UserInfo.User parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.sdw.soft.demo.protobuf.UserInfo.User parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.sdw.soft.demo.protobuf.UserInfo.User parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.sdw.soft.demo.protobuf.UserInfo.User prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.sdw.soft.demo.protobuf.User}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.sdw.soft.demo.protobuf.User)
        com.sdw.soft.demo.protobuf.UserInfo.UserOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.sdw.soft.demo.protobuf.UserInfo.internal_static_com_sdw_soft_demo_protobuf_User_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.sdw.soft.demo.protobuf.UserInfo.internal_static_com_sdw_soft_demo_protobuf_User_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.sdw.soft.demo.protobuf.UserInfo.User.class, com.sdw.soft.demo.protobuf.UserInfo.User.Builder.class);
      }

      // Construct using com.sdw.soft.demo.protobuf.UserInfo.User.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPhoneFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        email_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        if (phoneBuilder_ == null) {
          phone_ = com.sdw.soft.demo.protobuf.UserInfo.User.PhoneNumber.getDefaultInstance();
        } else {
          phoneBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.sdw.soft.demo.protobuf.UserInfo.internal_static_com_sdw_soft_demo_protobuf_User_descriptor;
      }

      public com.sdw.soft.demo.protobuf.UserInfo.User getDefaultInstanceForType() {
        return com.sdw.soft.demo.protobuf.UserInfo.User.getDefaultInstance();
      }

      public com.sdw.soft.demo.protobuf.UserInfo.User build() {
        com.sdw.soft.demo.protobuf.UserInfo.User result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.sdw.soft.demo.protobuf.UserInfo.User buildPartial() {
        com.sdw.soft.demo.protobuf.UserInfo.User result = new com.sdw.soft.demo.protobuf.UserInfo.User(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.email_ = email_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        if (phoneBuilder_ == null) {
          result.phone_ = phone_;
        } else {
          result.phone_ = phoneBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.sdw.soft.demo.protobuf.UserInfo.User) {
          return mergeFrom((com.sdw.soft.demo.protobuf.UserInfo.User)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.sdw.soft.demo.protobuf.UserInfo.User other) {
        if (other == com.sdw.soft.demo.protobuf.UserInfo.User.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasEmail()) {
          bitField0_ |= 0x00000004;
          email_ = other.email_;
          onChanged();
        }
        if (other.hasPhone()) {
          mergePhone(other.getPhone());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasName()) {
          
          return false;
        }
        if (!hasId()) {
          
          return false;
        }
        if (!hasEmail()) {
          
          return false;
        }
        if (!hasPhone()) {
          
          return false;
        }
        if (!getPhone().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.sdw.soft.demo.protobuf.UserInfo.User parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.sdw.soft.demo.protobuf.UserInfo.User) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      private int id_ ;
      /**
       * <code>required int32 id = 2;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 id = 2;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 2;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000002;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 2;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object email_ = "";
      /**
       * <code>required string email = 3;</code>
       */
      public boolean hasEmail() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string email = 3;</code>
       */
      public java.lang.String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            email_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string email = 3;</code>
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        java.lang.Object ref = email_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string email = 3;</code>
       */
      public Builder setEmail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        email_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string email = 3;</code>
       */
      public Builder clearEmail() {
        bitField0_ = (bitField0_ & ~0x00000004);
        email_ = getDefaultInstance().getEmail();
        onChanged();
        return this;
      }
      /**
       * <code>required string email = 3;</code>
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        email_ = value;
        onChanged();
        return this;
      }

      private com.sdw.soft.demo.protobuf.UserInfo.User.PhoneNumber phone_ = com.sdw.soft.demo.protobuf.UserInfo.User.PhoneNumber.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.sdw.soft.demo.protobuf.UserInfo.User.PhoneNumber, com.sdw.soft.demo.protobuf.UserInfo.User.PhoneNumber.Builder, com.sdw.soft.demo.protobuf.UserInfo.User.PhoneNumberOrBuilder> phoneBuilder_;
      /**
       * <code>required .com.sdw.soft.demo.protobuf.User.PhoneNumber phone = 4;</code>
       */
      public boolean hasPhone() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required .com.sdw.soft.demo.protobuf.User.PhoneNumber phone = 4;</code>
       */
      public com.sdw.soft.demo.protobuf.UserInfo.User.PhoneNumber getPhone() {
        if (phoneBuilder_ == null) {
          return phone_;
        } else {
          return phoneBuilder_.getMessage();
        }
      }
      /**
       * <code>required .com.sdw.soft.demo.protobuf.User.PhoneNumber phone = 4;</code>
       */
      public Builder setPhone(com.sdw.soft.demo.protobuf.UserInfo.User.PhoneNumber value) {
        if (phoneBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          phone_ = value;
          onChanged();
        } else {
          phoneBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>required .com.sdw.soft.demo.protobuf.User.PhoneNumber phone = 4;</code>
       */
      public Builder setPhone(
          com.sdw.soft.demo.protobuf.UserInfo.User.PhoneNumber.Builder builderForValue) {
        if (phoneBuilder_ == null) {
          phone_ = builderForValue.build();
          onChanged();
        } else {
          phoneBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>required .com.sdw.soft.demo.protobuf.User.PhoneNumber phone = 4;</code>
       */
      public Builder mergePhone(com.sdw.soft.demo.protobuf.UserInfo.User.PhoneNumber value) {
        if (phoneBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008) &&
              phone_ != com.sdw.soft.demo.protobuf.UserInfo.User.PhoneNumber.getDefaultInstance()) {
            phone_ =
              com.sdw.soft.demo.protobuf.UserInfo.User.PhoneNumber.newBuilder(phone_).mergeFrom(value).buildPartial();
          } else {
            phone_ = value;
          }
          onChanged();
        } else {
          phoneBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>required .com.sdw.soft.demo.protobuf.User.PhoneNumber phone = 4;</code>
       */
      public Builder clearPhone() {
        if (phoneBuilder_ == null) {
          phone_ = com.sdw.soft.demo.protobuf.UserInfo.User.PhoneNumber.getDefaultInstance();
          onChanged();
        } else {
          phoneBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      /**
       * <code>required .com.sdw.soft.demo.protobuf.User.PhoneNumber phone = 4;</code>
       */
      public com.sdw.soft.demo.protobuf.UserInfo.User.PhoneNumber.Builder getPhoneBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getPhoneFieldBuilder().getBuilder();
      }
      /**
       * <code>required .com.sdw.soft.demo.protobuf.User.PhoneNumber phone = 4;</code>
       */
      public com.sdw.soft.demo.protobuf.UserInfo.User.PhoneNumberOrBuilder getPhoneOrBuilder() {
        if (phoneBuilder_ != null) {
          return phoneBuilder_.getMessageOrBuilder();
        } else {
          return phone_;
        }
      }
      /**
       * <code>required .com.sdw.soft.demo.protobuf.User.PhoneNumber phone = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.sdw.soft.demo.protobuf.UserInfo.User.PhoneNumber, com.sdw.soft.demo.protobuf.UserInfo.User.PhoneNumber.Builder, com.sdw.soft.demo.protobuf.UserInfo.User.PhoneNumberOrBuilder> 
          getPhoneFieldBuilder() {
        if (phoneBuilder_ == null) {
          phoneBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.sdw.soft.demo.protobuf.UserInfo.User.PhoneNumber, com.sdw.soft.demo.protobuf.UserInfo.User.PhoneNumber.Builder, com.sdw.soft.demo.protobuf.UserInfo.User.PhoneNumberOrBuilder>(
                  getPhone(),
                  getParentForChildren(),
                  isClean());
          phone_ = null;
        }
        return phoneBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.sdw.soft.demo.protobuf.User)
    }

    static {
      defaultInstance = new User(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.sdw.soft.demo.protobuf.User)
  }

  public interface AddressBookOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.sdw.soft.demo.protobuf.AddressBook)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .com.sdw.soft.demo.protobuf.User user = 1;</code>
     */
    java.util.List<com.sdw.soft.demo.protobuf.UserInfo.User> 
        getUserList();
    /**
     * <code>repeated .com.sdw.soft.demo.protobuf.User user = 1;</code>
     */
    com.sdw.soft.demo.protobuf.UserInfo.User getUser(int index);
    /**
     * <code>repeated .com.sdw.soft.demo.protobuf.User user = 1;</code>
     */
    int getUserCount();
    /**
     * <code>repeated .com.sdw.soft.demo.protobuf.User user = 1;</code>
     */
    java.util.List<? extends com.sdw.soft.demo.protobuf.UserInfo.UserOrBuilder> 
        getUserOrBuilderList();
    /**
     * <code>repeated .com.sdw.soft.demo.protobuf.User user = 1;</code>
     */
    com.sdw.soft.demo.protobuf.UserInfo.UserOrBuilder getUserOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.sdw.soft.demo.protobuf.AddressBook}
   */
  public static final class AddressBook extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.sdw.soft.demo.protobuf.AddressBook)
      AddressBookOrBuilder {
    // Use AddressBook.newBuilder() to construct.
    private AddressBook(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private AddressBook(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final AddressBook defaultInstance;
    public static AddressBook getDefaultInstance() {
      return defaultInstance;
    }

    public AddressBook getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private AddressBook(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                user_ = new java.util.ArrayList<com.sdw.soft.demo.protobuf.UserInfo.User>();
                mutable_bitField0_ |= 0x00000001;
              }
              user_.add(input.readMessage(com.sdw.soft.demo.protobuf.UserInfo.User.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          user_ = java.util.Collections.unmodifiableList(user_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sdw.soft.demo.protobuf.UserInfo.internal_static_com_sdw_soft_demo_protobuf_AddressBook_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sdw.soft.demo.protobuf.UserInfo.internal_static_com_sdw_soft_demo_protobuf_AddressBook_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sdw.soft.demo.protobuf.UserInfo.AddressBook.class, com.sdw.soft.demo.protobuf.UserInfo.AddressBook.Builder.class);
    }

    public static com.google.protobuf.Parser<AddressBook> PARSER =
        new com.google.protobuf.AbstractParser<AddressBook>() {
      public AddressBook parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AddressBook(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<AddressBook> getParserForType() {
      return PARSER;
    }

    public static final int USER_FIELD_NUMBER = 1;
    private java.util.List<com.sdw.soft.demo.protobuf.UserInfo.User> user_;
    /**
     * <code>repeated .com.sdw.soft.demo.protobuf.User user = 1;</code>
     */
    public java.util.List<com.sdw.soft.demo.protobuf.UserInfo.User> getUserList() {
      return user_;
    }
    /**
     * <code>repeated .com.sdw.soft.demo.protobuf.User user = 1;</code>
     */
    public java.util.List<? extends com.sdw.soft.demo.protobuf.UserInfo.UserOrBuilder> 
        getUserOrBuilderList() {
      return user_;
    }
    /**
     * <code>repeated .com.sdw.soft.demo.protobuf.User user = 1;</code>
     */
    public int getUserCount() {
      return user_.size();
    }
    /**
     * <code>repeated .com.sdw.soft.demo.protobuf.User user = 1;</code>
     */
    public com.sdw.soft.demo.protobuf.UserInfo.User getUser(int index) {
      return user_.get(index);
    }
    /**
     * <code>repeated .com.sdw.soft.demo.protobuf.User user = 1;</code>
     */
    public com.sdw.soft.demo.protobuf.UserInfo.UserOrBuilder getUserOrBuilder(
        int index) {
      return user_.get(index);
    }

    private void initFields() {
      user_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getUserCount(); i++) {
        if (!getUser(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < user_.size(); i++) {
        output.writeMessage(1, user_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < user_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, user_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.sdw.soft.demo.protobuf.UserInfo.AddressBook parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sdw.soft.demo.protobuf.UserInfo.AddressBook parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sdw.soft.demo.protobuf.UserInfo.AddressBook parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sdw.soft.demo.protobuf.UserInfo.AddressBook parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sdw.soft.demo.protobuf.UserInfo.AddressBook parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.sdw.soft.demo.protobuf.UserInfo.AddressBook parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.sdw.soft.demo.protobuf.UserInfo.AddressBook parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.sdw.soft.demo.protobuf.UserInfo.AddressBook parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.sdw.soft.demo.protobuf.UserInfo.AddressBook parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.sdw.soft.demo.protobuf.UserInfo.AddressBook parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.sdw.soft.demo.protobuf.UserInfo.AddressBook prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.sdw.soft.demo.protobuf.AddressBook}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.sdw.soft.demo.protobuf.AddressBook)
        com.sdw.soft.demo.protobuf.UserInfo.AddressBookOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.sdw.soft.demo.protobuf.UserInfo.internal_static_com_sdw_soft_demo_protobuf_AddressBook_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.sdw.soft.demo.protobuf.UserInfo.internal_static_com_sdw_soft_demo_protobuf_AddressBook_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.sdw.soft.demo.protobuf.UserInfo.AddressBook.class, com.sdw.soft.demo.protobuf.UserInfo.AddressBook.Builder.class);
      }

      // Construct using com.sdw.soft.demo.protobuf.UserInfo.AddressBook.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getUserFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (userBuilder_ == null) {
          user_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          userBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.sdw.soft.demo.protobuf.UserInfo.internal_static_com_sdw_soft_demo_protobuf_AddressBook_descriptor;
      }

      public com.sdw.soft.demo.protobuf.UserInfo.AddressBook getDefaultInstanceForType() {
        return com.sdw.soft.demo.protobuf.UserInfo.AddressBook.getDefaultInstance();
      }

      public com.sdw.soft.demo.protobuf.UserInfo.AddressBook build() {
        com.sdw.soft.demo.protobuf.UserInfo.AddressBook result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.sdw.soft.demo.protobuf.UserInfo.AddressBook buildPartial() {
        com.sdw.soft.demo.protobuf.UserInfo.AddressBook result = new com.sdw.soft.demo.protobuf.UserInfo.AddressBook(this);
        int from_bitField0_ = bitField0_;
        if (userBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            user_ = java.util.Collections.unmodifiableList(user_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.user_ = user_;
        } else {
          result.user_ = userBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.sdw.soft.demo.protobuf.UserInfo.AddressBook) {
          return mergeFrom((com.sdw.soft.demo.protobuf.UserInfo.AddressBook)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.sdw.soft.demo.protobuf.UserInfo.AddressBook other) {
        if (other == com.sdw.soft.demo.protobuf.UserInfo.AddressBook.getDefaultInstance()) return this;
        if (userBuilder_ == null) {
          if (!other.user_.isEmpty()) {
            if (user_.isEmpty()) {
              user_ = other.user_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureUserIsMutable();
              user_.addAll(other.user_);
            }
            onChanged();
          }
        } else {
          if (!other.user_.isEmpty()) {
            if (userBuilder_.isEmpty()) {
              userBuilder_.dispose();
              userBuilder_ = null;
              user_ = other.user_;
              bitField0_ = (bitField0_ & ~0x00000001);
              userBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getUserFieldBuilder() : null;
            } else {
              userBuilder_.addAllMessages(other.user_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getUserCount(); i++) {
          if (!getUser(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.sdw.soft.demo.protobuf.UserInfo.AddressBook parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.sdw.soft.demo.protobuf.UserInfo.AddressBook) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.sdw.soft.demo.protobuf.UserInfo.User> user_ =
        java.util.Collections.emptyList();
      private void ensureUserIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          user_ = new java.util.ArrayList<com.sdw.soft.demo.protobuf.UserInfo.User>(user_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.sdw.soft.demo.protobuf.UserInfo.User, com.sdw.soft.demo.protobuf.UserInfo.User.Builder, com.sdw.soft.demo.protobuf.UserInfo.UserOrBuilder> userBuilder_;

      /**
       * <code>repeated .com.sdw.soft.demo.protobuf.User user = 1;</code>
       */
      public java.util.List<com.sdw.soft.demo.protobuf.UserInfo.User> getUserList() {
        if (userBuilder_ == null) {
          return java.util.Collections.unmodifiableList(user_);
        } else {
          return userBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.sdw.soft.demo.protobuf.User user = 1;</code>
       */
      public int getUserCount() {
        if (userBuilder_ == null) {
          return user_.size();
        } else {
          return userBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.sdw.soft.demo.protobuf.User user = 1;</code>
       */
      public com.sdw.soft.demo.protobuf.UserInfo.User getUser(int index) {
        if (userBuilder_ == null) {
          return user_.get(index);
        } else {
          return userBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.sdw.soft.demo.protobuf.User user = 1;</code>
       */
      public Builder setUser(
          int index, com.sdw.soft.demo.protobuf.UserInfo.User value) {
        if (userBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUserIsMutable();
          user_.set(index, value);
          onChanged();
        } else {
          userBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.sdw.soft.demo.protobuf.User user = 1;</code>
       */
      public Builder setUser(
          int index, com.sdw.soft.demo.protobuf.UserInfo.User.Builder builderForValue) {
        if (userBuilder_ == null) {
          ensureUserIsMutable();
          user_.set(index, builderForValue.build());
          onChanged();
        } else {
          userBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.sdw.soft.demo.protobuf.User user = 1;</code>
       */
      public Builder addUser(com.sdw.soft.demo.protobuf.UserInfo.User value) {
        if (userBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUserIsMutable();
          user_.add(value);
          onChanged();
        } else {
          userBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.sdw.soft.demo.protobuf.User user = 1;</code>
       */
      public Builder addUser(
          int index, com.sdw.soft.demo.protobuf.UserInfo.User value) {
        if (userBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUserIsMutable();
          user_.add(index, value);
          onChanged();
        } else {
          userBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.sdw.soft.demo.protobuf.User user = 1;</code>
       */
      public Builder addUser(
          com.sdw.soft.demo.protobuf.UserInfo.User.Builder builderForValue) {
        if (userBuilder_ == null) {
          ensureUserIsMutable();
          user_.add(builderForValue.build());
          onChanged();
        } else {
          userBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.sdw.soft.demo.protobuf.User user = 1;</code>
       */
      public Builder addUser(
          int index, com.sdw.soft.demo.protobuf.UserInfo.User.Builder builderForValue) {
        if (userBuilder_ == null) {
          ensureUserIsMutable();
          user_.add(index, builderForValue.build());
          onChanged();
        } else {
          userBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.sdw.soft.demo.protobuf.User user = 1;</code>
       */
      public Builder addAllUser(
          java.lang.Iterable<? extends com.sdw.soft.demo.protobuf.UserInfo.User> values) {
        if (userBuilder_ == null) {
          ensureUserIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, user_);
          onChanged();
        } else {
          userBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.sdw.soft.demo.protobuf.User user = 1;</code>
       */
      public Builder clearUser() {
        if (userBuilder_ == null) {
          user_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          userBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.sdw.soft.demo.protobuf.User user = 1;</code>
       */
      public Builder removeUser(int index) {
        if (userBuilder_ == null) {
          ensureUserIsMutable();
          user_.remove(index);
          onChanged();
        } else {
          userBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.sdw.soft.demo.protobuf.User user = 1;</code>
       */
      public com.sdw.soft.demo.protobuf.UserInfo.User.Builder getUserBuilder(
          int index) {
        return getUserFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.sdw.soft.demo.protobuf.User user = 1;</code>
       */
      public com.sdw.soft.demo.protobuf.UserInfo.UserOrBuilder getUserOrBuilder(
          int index) {
        if (userBuilder_ == null) {
          return user_.get(index);  } else {
          return userBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.sdw.soft.demo.protobuf.User user = 1;</code>
       */
      public java.util.List<? extends com.sdw.soft.demo.protobuf.UserInfo.UserOrBuilder> 
           getUserOrBuilderList() {
        if (userBuilder_ != null) {
          return userBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(user_);
        }
      }
      /**
       * <code>repeated .com.sdw.soft.demo.protobuf.User user = 1;</code>
       */
      public com.sdw.soft.demo.protobuf.UserInfo.User.Builder addUserBuilder() {
        return getUserFieldBuilder().addBuilder(
            com.sdw.soft.demo.protobuf.UserInfo.User.getDefaultInstance());
      }
      /**
       * <code>repeated .com.sdw.soft.demo.protobuf.User user = 1;</code>
       */
      public com.sdw.soft.demo.protobuf.UserInfo.User.Builder addUserBuilder(
          int index) {
        return getUserFieldBuilder().addBuilder(
            index, com.sdw.soft.demo.protobuf.UserInfo.User.getDefaultInstance());
      }
      /**
       * <code>repeated .com.sdw.soft.demo.protobuf.User user = 1;</code>
       */
      public java.util.List<com.sdw.soft.demo.protobuf.UserInfo.User.Builder> 
           getUserBuilderList() {
        return getUserFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.sdw.soft.demo.protobuf.UserInfo.User, com.sdw.soft.demo.protobuf.UserInfo.User.Builder, com.sdw.soft.demo.protobuf.UserInfo.UserOrBuilder> 
          getUserFieldBuilder() {
        if (userBuilder_ == null) {
          userBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.sdw.soft.demo.protobuf.UserInfo.User, com.sdw.soft.demo.protobuf.UserInfo.User.Builder, com.sdw.soft.demo.protobuf.UserInfo.UserOrBuilder>(
                  user_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          user_ = null;
        }
        return userBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.sdw.soft.demo.protobuf.AddressBook)
    }

    static {
      defaultInstance = new AddressBook(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.sdw.soft.demo.protobuf.AddressBook)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_sdw_soft_demo_protobuf_User_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_sdw_soft_demo_protobuf_User_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_sdw_soft_demo_protobuf_User_PhoneNumber_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_sdw_soft_demo_protobuf_User_PhoneNumber_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_sdw_soft_demo_protobuf_AddressBook_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_sdw_soft_demo_protobuf_AddressBook_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016userinfo.proto\022\032com.sdw.soft.demo.prot" +
      "obuf\"\370\001\n\004User\022\014\n\004name\030\001 \002(\t\022\n\n\002id\030\002 \002(\005\022" +
      "\r\n\005email\030\003 \002(\t\022;\n\005phone\030\004 \002(\0132,.com.sdw." +
      "soft.demo.protobuf.User.PhoneNumber\032]\n\013P" +
      "honeNumber\022\016\n\006number\030\001 \002(\t\022>\n\004type\030\002 \001(\016" +
      "2*.com.sdw.soft.demo.protobuf.User.Phone" +
      "Type:\004HOME\"+\n\tPhoneType\022\n\n\006MOBILE\020\000\022\010\n\004H" +
      "OME\020\001\022\010\n\004WORK\020\002\"=\n\013AddressBook\022.\n\004user\030\001" +
      " \003(\0132 .com.sdw.soft.demo.protobuf.UserB&" +
      "\n\032com.sdw.soft.demo.protobufB\010UserInfo"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_sdw_soft_demo_protobuf_User_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_sdw_soft_demo_protobuf_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_sdw_soft_demo_protobuf_User_descriptor,
        new java.lang.String[] { "Name", "Id", "Email", "Phone", });
    internal_static_com_sdw_soft_demo_protobuf_User_PhoneNumber_descriptor =
      internal_static_com_sdw_soft_demo_protobuf_User_descriptor.getNestedTypes().get(0);
    internal_static_com_sdw_soft_demo_protobuf_User_PhoneNumber_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_sdw_soft_demo_protobuf_User_PhoneNumber_descriptor,
        new java.lang.String[] { "Number", "Type", });
    internal_static_com_sdw_soft_demo_protobuf_AddressBook_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_sdw_soft_demo_protobuf_AddressBook_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_sdw_soft_demo_protobuf_AddressBook_descriptor,
        new java.lang.String[] { "User", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
